service_name: mongodb 
backup_base_dir: /mnt/nfs/servicebackup/
# the following is for test purpose 
local_db: sqlite3:/tmp/mongo/mongodb_node.db
service_base_dir: /var/vcap/services/mongodb/instances/
log_level: DEBUG 
fail_mail: figof@mozy.com

